AllCops:
    NewCops: enable

Layout/MultilineMethodCallIndentation:
    EnforcedStyle: indented

Naming/MethodParameterName:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericPredicate:
    Enabled: false
